
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author sahilgupta2317
 */
public class home extends javax.swing.JFrame {
    public int i=0;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        locbtn = new javax.swing.JButton();
        newrecordbtn = new javax.swing.JButton();
        addinfobtn = new javax.swing.JButton();
        historybtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        hospinfobtn = new javax.swing.JButton();
        logoutbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        locbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/two arrow.png"))); // NOI18N
        locbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        locbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locbtnActionPerformed(evt);
            }
        });
        getContentPane().add(locbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 31, 80, -1));

        newrecordbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add new patient.png"))); // NOI18N
        newrecordbtn.setText("Add New Patient Record");
        newrecordbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        newrecordbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newrecordbtnActionPerformed(evt);
            }
        });
        getContentPane().add(newrecordbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 122, -1, -1));

        addinfobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add diag.png"))); // NOI18N
        addinfobtn.setText("Add Diagnosis Information");
        addinfobtn.setPreferredSize(new java.awt.Dimension(240, 59));
        addinfobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addinfobtnActionPerformed(evt);
            }
        });
        getContentPane().add(addinfobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        historybtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_history1.png"))); // NOI18N
        historybtn.setText("Full History of the Patient");
        historybtn.setPreferredSize(new java.awt.Dimension(240, 59));
        historybtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historybtnActionPerformed(evt);
            }
        });
        getContentPane().add(historybtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        updatebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_update_details.png"))); // NOI18N
        updatebtn.setText("Update Patient Record");
        updatebtn.setPreferredSize(new java.awt.Dimension(240, 59));
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });
        getContentPane().add(updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        hospinfobtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rsz_hospital_information.png"))); // NOI18N
        hospinfobtn.setText("Hospital Information");
        hospinfobtn.setPreferredSize(new java.awt.Dimension(240, 59));
        hospinfobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospinfobtnActionPerformed(evt);
            }
        });
        getContentPane().add(hospinfobtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));

        logoutbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        logoutbtn.setText("Logout");
        logoutbtn.setPreferredSize(new java.awt.Dimension(240, 59));
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        getContentPane().add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/home.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really want to logout","Select",JOptionPane.YES_NO_OPTION);
        if(a==0)
        {
           setVisible(false);
           new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void locbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locbtnActionPerformed
        // TODO add your handling code here:
        if(i==0)
        {
           newrecordbtn.setLocation(90,30); 
           addinfobtn.setLocation(333,30);
           historybtn.setLocation(576,30);
           updatebtn.setLocation(819,30);
           hospinfobtn.setLocation(1062,30);
           logoutbtn.setLocation(90,100);
           i=1;  
        }
        else
        {
             newrecordbtn.setLocation(10,107); 
           addinfobtn.setLocation(10,184);
           historybtn.setLocation(10,261);
           updatebtn.setLocation(10,338);
           hospinfobtn.setLocation(10,415);
           logoutbtn.setLocation(10,490);
            i=0;
        }
    }//GEN-LAST:event_locbtnActionPerformed

    private void newrecordbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newrecordbtnActionPerformed
        // TODO add your handling code here:
        new addNewPatientRecord().setVisible(true);
    }//GEN-LAST:event_newrecordbtnActionPerformed

    private void addinfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addinfobtnActionPerformed
        // TODO add your handling code here:
        new addDiagnosisInformation().setVisible(true);
    }//GEN-LAST:event_addinfobtnActionPerformed

    private void historybtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historybtnActionPerformed
        // TODO add your handling code here:
        new fullHistoryOfThePatient().setVisible(true);
    }//GEN-LAST:event_historybtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
        // TODO add your handling code here:
        new updatePatientRecord().setVisible(true);
    }//GEN-LAST:event_updatebtnActionPerformed

    private void hospinfobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospinfobtnActionPerformed
        // TODO add your handling code here:
        new hospitalInformation().setVisible(true);
    }//GEN-LAST:event_hospinfobtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addinfobtn;
    private javax.swing.JButton historybtn;
    private javax.swing.JButton hospinfobtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton locbtn;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton newrecordbtn;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
